### ISSUE TITLE
Add option to disable link to latest URL generated

### ISSUE THREAD

**Issue by eibex** [132ikl/liteshort#13]
Being able to access the latest URLs does not seem very privacy friendly. I am currently using a dirty work around that consists of setting the `latest` option to a randomised 128-character string. 

It would be nice if it was possible to avoid generating this link altogether (maybe not specifying anything would result in this instead of defaulting to `l`?).

**Comment by 132ikl** [comment]
Unset `latest` option in config.yml to disable latest link, eg.
`latest: 'l'` -> `latest:`
