### ISSUE TITLE
Add optional link expiration

### ISSUE THREAD

**Issue by eibex** [132ikl/liteshort#19]
I find myself often creating a short link only to delete it after no longer having a need for it or not wanting people to still access it.

Therefore, I thought of adding a link expiration dropdown menu could be beneficial. The idea I have in mind is very similar to the one of that [andreimarcu/linx-server](https://github.com/andreimarcu/linx-server) implemented it (see screenshot). The dropdown could default to "Never", but show choices such as as 1 hour, 1 day, etc.

![image](https://user-images.githubusercontent.com/40539455/77961828-c31b3a80-72da-11ea-8f62-75cf49df01ba.png)

**Comment by 132ikl** [comment]
Moved to https://git.ikl.sh/132ikl/liteshort/issues/19
