### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by ghost** [132ikl/liteshort#2]
Are there any plans to create a Docker container for this application?

**Comment by 132ikl** [comment]
I hadn't even thought of it, but if there is interest for it then I will consider it.

**Comment by whalehub** [comment]
I would be interested in one.

**Comment by jtagcat** [comment]
If liteshort would've have docker I would use it, right now gonna use [lstu](https://framagit.org/fiat-tux/hat-softwares/lstu) instead.

**Comment by 132ikl** [comment]
Alright, good to hear there is interest. Actually, lstu is the reason why liteshort exists :)

**Comment by ThomasLachaux** [comment]
I've just finished to dockerize the application. (the README is a bit dirty).

https://github.com/ThomasLachaux/liteshort
https://hub.docker.com/r/thomaslachaux/liteshort

The idea is to use 2 containers: one for the app and one for nginx. I advise you to use nginx proxy to avoid static ip.

Have a nice day !

**Comment by 132ikl** [comment]
Is there a reason for not just including the nginx server in the main image?

**Comment by ThomasLachaux** [comment]
Because it's the Docker philosophy ;) https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#decouple-applications. You should have one container per main process.

**Comment by 132ikl** [comment]
Very nice, I'll test it out and then add it into docs. (might even use it for my instance ;))
