### ISSUE TITLE
Question : maximum combinations of short links

### ISSUE THREAD

**Issue by starfish1337** [132ikl/liteshort#8]
`random_length: 4`

with that value set as default, does the random URL generator generate only 4 characters, or switches to more than 4 characters when all 4 character combinations are exhausted?

in other words, what's the maximum combinations that can be generated with liteshort?

**Comment by 132ikl** [comment]
The URL generator only generates 4 characters. If it fails to generate a unique URL before it times out (default 5 seconds) then it will return an error. The default character set is 65 characters long, so the amount of unique URLs at 4 characters is 65^4, or 17850625. However, I would not be opposed to allowing longer URLs if all of the unique URLs at the specified character length are used.
