### ISSUE TITLE
API delete returns success but does not actually delete the URL

### ISSUE THREAD

**Issue by eibex** [132ikl/liteshort#9]
Requesting an URL deletion does not work as intended, both with `long` and `short` data.

```
curl -u user:pwd -d 'format=json' -d 'api=delete' -d 'long=https://longurl.com' https://example.com
```
This does not seem to do anything even though it returns success. The links that point to this URL keep working.

```
curl -u user:pwd -d 'format=json' -d 'api=delete' -d 'short=short4chars' https://example.com
```
This deletes the shorturl, but a new one is created if you try to delete the long URL it was pointing to.

**Comment by 132ikl** [comment]
Hi, I can't reproduce this on my instance. Could you send your configuration, and if possible your database file?

**Comment by eibex** [comment]
I just noticed the reason was the latest short URL link was not shown when asking for a list of URLs with the API unless the database was empty. Sorry for the issue.
